# Generated by Django 4.2.5 on 2023-10-11 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skaaltec_test9', '0003_patienthastherapist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('textMessage', models.TextField()),
                ('sender', models.CharField(max_length=250)),
                ('receiver', models.CharField(max_length=250)),
                ('new_message', models.BooleanField(default=True)),
                ('patientAndTherapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skaaltec_test9.patienthastherapist')),
            ],
        ),
    ]
