# Generated by Django 4.2.5 on 2023-10-16 08:12

from django.db import migrations, models
import django.db.models.deletion
import skaaltec_test9.models


class Migration(migrations.Migration):

    dependencies = [
        ('skaaltec_test9', '0007_remove_session_color_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_code', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('data_file', models.FileField(blank=True, upload_to=skaaltec_test9.models.update_filename)),
                ('patientAndTherapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skaaltec_test9.patienthastherapist')),
            ],
        ),
    ]
